version: '3.8'
services:
  redis-server:
    image: redis/redis-stack-server:latest
    container_name: redis-server
    ports:
      - "6379:6379"  # Exponiendo el puerto para acceder desde fuera del contenedor
    volumes: 
      - ./data:/data
    networks:
      - redis-network

  redis-client:
    image: redis:latest
    container_name: redis-client
    command: ["redis-cli", "-h", "redis-server"]
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge
